development:
  adapter: async
  url: redis://#{ENV["REDIS_HOST"]}:#{ENV["REDIS_PORT"]}/0
  channel_prefix: tanager_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://#{ENV["REDIS_HOST"]}:#{ENV["REDIS_PORT"]}/0
  channel_prefix: tanager_production